version: '3.0'

services:
  zookeeper:
    image: arm64v8/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_SECURITY_INTER_BROKER_PROTOCOL: PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    depends_on:
      - zookeeper

  producer:
    build:
      context: .
      dockerfile: Dockerfile_producer
    volumes:
      - ./data:/app/data

  consumer:
    build:
      context: .
      dockerfile: Dockerfile_consumer
    volumes:
      - ./data:/app/data
